### ISSUE TITLE
MOD 编译出错

### ISSUE THREAD

**Issue by yehx1** [ricequant/rqalpha#102]
我做了一下mod的官方例子helloworld，我首先在mod文件夹下建了一个rqalpha_mod_hello_world文件夹，然后建了相应的__init__的文件，然后在mod_config_template.yml文件中加入mod的

```
mod:
  hello_world:
    lib: 'rqalpha.mod.hello_world'
    enabled: true
    priority: 100
```

但是仍然提示 `Mod Import Error:`
请问有什么其他的需要注意的吗？（我的rqalpha的版本是2.0.9）
