### ISSUE TITLE
配置文件不起作用

### ISSUE THREAD

**Issue by prisoner** [ricequant/rqalpha#176]
## 1. RQAlpha的版本

3.0.2

## 2. Python的版本

Python 3.5.2+

## 3. 是Windows/Linux/MacOS or others?

Ubuntu 16.10

## 4. 出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置

配置文件config.yml位于当前目录。
使用`rqalpha run`或`rqalpha run -f buy_and_hold.py --config config.yml`都报错。
home目录下没有配置文件。
配置文件：
```
# see more config
# http://rqalpha.readthedocs.io/zh_CN/stable/intro/run_algorithm.html
version: 0.1.6

# 白名单，设置可以直接在策略代码中指定哪些模块的配置项目
whitelist: [base, extra, validator, mod]

base:
  # 数据源所存储的文件路径
#  data_bundle_path: ~/.rqalpha/bundle/
  # 启动的策略文件路径
#  strategy_file: strategy.py
  # 策略源代码
#  source_code: ~
  # 回测起始日期
  start_date: 2015-01-01
  # 回测结束日期(如果是实盘，则忽略该配置)
  end_date: 2017-01-01
  # 设置保证金乘数，默认为1
  margin_multiplier: 1
  # 运行类型，`b` 为回测，`p` 为模拟交易, `r` 为实盘交易。
  run_type: b
  # 目前支持 `1d` (日线回测) 和 `1m` (分钟线回测)，如果要进行分钟线，请注意是否拥有对应的数据源，目前开源版本是不提供对应的数据源的。
  frequency: 1d
  # Benchmark，如果不设置，默认没有基准参照。
  benchmark: '000300.XSHG'
  # 在模拟交易和实盘交易中，RQAlpha支持策略的pause && resume，该选项表示开启 resume 功能
  resume_mode: false
  # 在模拟交易和实盘交易中，RQAlpha支持策略的pause && resume，该选项表示开启 persist 功能呢，
  # 其会在每个bar结束对进行策略的持仓、账户信息，用户的代码上线文等内容进行持久化
  persist: false
  persist_mode: real_time
  # 设置策略可交易品种，目前支持 `stock` (股票账户)、`future` (期货账户)，您也可以自行扩展
  accounts:
    # 如果想设置使用某个账户，只需要增加对应的初始资金即可
    stock: 50000
#    future: ~

extra:
  # 选择日期的输出等级，有 `verbose` | `info` | `warning` | `error` 等选项，您可以通过设置 `verbose` 来查看最详细的日志，
  # 或者设置 `error` 只查看错误级别的日志输出
  log_level: verbose
  user_system_log_disabled: false
  user_log_disabled: false
  # 通过该参数可以将预定义变量传入 `context` 内。
  context_vars: ~
  # force_run_init_when_pt_resume: 在PT的resume模式时，是否强制执行用户init。主要用于用户改代码。
  force_run_init_when_pt_resume: false
  # enable_profiler: 是否启动性能分析
  enable_profiler: false
  is_hold: false
  locale: zh_Hans_CN

validator:
  # cash_return_by_stock_delisted: 开启该项，当持仓股票退市时，按照退市价格返还现金
  cash_return_by_stock_delisted: true
  # close_amount: 在执行order_value操作时，进行实际下单数量的校验和scale，默认开启
  close_amount: true

```
## 5. 出现的错误堆栈日志信息

```
Traceback (most recent call last):
  File "/mnt/p5/virtualenvs/p35/bin/rqalpha", line 11, in <module>
    sys.exit(entry_point())
    │        └ <function entry_point at 0x7f1ccc51aa60>
    └ <module 'sys' (built-in)>
  File "/mnt/p5/virtualenvs/p35/lib/python3.5/site-packages/rqalpha/__main__.py", line 70, in entry_point
    cli(obj={})
    └ <click.core.Group object at 0x7f1ccc4feef0>
  File "/mnt/p5/virtualenvs/p35/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
           │          │       └ {'obj': {'VERBOSE': 0}}
           │          └ ()
           └ <click.core.Group object at 0x7f1ccc4feef0>
  File "/mnt/p5/virtualenvs/p35/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
         │           └ <click.core.Context object at 0x7f1ccc4988d0>
         └ <click.core.Group object at 0x7f1ccc4feef0>
  File "/mnt/p5/virtualenvs/p35/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │                      └ <click.core.Context object at 0x7f1ccc437e80>
           │               └ <click.core.Context object at 0x7f1ccc437e80>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f1cdea0a268>
  File "/mnt/p5/virtualenvs/p35/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │          │                └ <click.core.Context object at 0x7f1ccc437e80>
           │          └ <click.core.Command object at 0x7f1ccc51bb00>
           └ <click.core.Context object at 0x7f1ccc437e80>
  File "/mnt/p5/virtualenvs/p35/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'mod__sys_analyser__plot': None, 'config_path': 'config.yml', 'base__accounts': (), 'mod__sys_analyser__output_file': None, 'mo...
           │         └ ()
           └ <function run at 0x7f1ccc51d840>
  File "/mnt/p5/virtualenvs/p35/lib/python3.5/site-packages/rqalpha/__main__.py", line 121, in run
    cfg = parse_config(kwargs, config_path=config_path, click_type=True, source_code=source_code)
          │            │                   │                                         └ None
          │            │                   └ '/home/********/code/workspace/rqalpha/config.yml'
          │            └ {'mod__sys_analyser__plot': None, 'base__accounts': (), 'mod__sys_analyser__output_file': None, 'mod__sys_analyser__plot_save_fi...
          └ <function parse_config at 0x7f1ccc51a7b8>
  File "/mnt/p5/virtualenvs/p35/lib/python3.5/site-packages/rqalpha/utils/config.py", line 205, in parse_config
    base_config.accounts = parse_accounts(base_config.accounts)
    │                      │              └ {'accounts': (),
 'benchmark': '000300.XSHG',
 'data_bundle_path': '/home/********/.rqalpha/bundle',
 'end_date': datetime.date(...
    │                      └ <function parse_accounts at 0x7f1ccc51a8c8>
    └ {'accounts': (),
 'benchmark': '000300.XSHG',
 'data_bundle_path': '/home/********/.rqalpha/bundle',
 'end_date': datetime.date(...
  File "/mnt/p5/virtualenvs/p35/lib/python3.5/site-packages/rqalpha/utils/config.py", line 259, in parse_accounts
    raise RuntimeError(_('None account type has been selected.'"))
                       └ <function gettext at 0x7f1cddd1d378>
RuntimeError: 请设置账户及初始资金
```
