### ISSUE TITLE
plt.show() 堵塞程序,  导致不能正常保存图片 plt.savefig

### ISSUE THREAD

**Issue by yssource** [ricequant/rqalpha#224]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
latest develop branch
## 2. Python的版本
py3.6
## 3. 是Windows/Linux/MacOS or others?
Linux
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置

```
mod:
  sys_analyser:
    enabled: true
    # 开启 plot 功能
    plot: true
    output_file: /tmp/rq.pkl
    plot_save_file: /tmp/rq.png
    report_save_path: /tmp

```

`rqalpha run` 

先执行 [plt.show()](https://github.com/ricequant/rqalpha/blob/develop/rqalpha/mod/rqalpha_mod_sys_analyser/plot.py#L183)  后, 跳出 plt 交互图, 程序会在这里都塞. 
只有关闭 plt 交互图后, 才会继续后面的
[if savefile:](https://github.com/ricequant/rqalpha/blob/develop/rqalpha/mod/rqalpha_mod_sys_analyser/plot.py#L185)

结果是, 关闭 plt 交互图后, 不能正常保存 /tmp/rq.png. 此图片会正常生成, 但是打开时是一片空白的图片.

`rqalpha plot /tmp/rq.pkl --show --plot-save /tmp/rq.png` 会带来同样的结果.

`rqalpha plot /tmp/rq.pkl --hide --plot-save /tmp/rq.png` 不同的结果, 图片正常保存和打开.

个人建议:

[修改这里](https://github.com/ricequant/rqalpha/blob/develop/rqalpha/mod/rqalpha_mod_sys_analyser/plot.py#L182-L189)

将 `if savefile:` 放 `if show_windows:` 前面

```
    if savefile:
        fnmame = savefile
        if os.path.isdir(savefile):
            fnmame = os.path.join(savefile, "{}.png".format(summary["strategy_name"]))
        plt.savefig(fnmame, bbox_inches='tight')

    if show_windows:
        plt.show()
```
