### ISSUE TITLE
为啥 context.now 取到的不是当前 **实盘实际运行时间**?

### ISSUE THREAD

**Issue by yssource** [ricequant/rqalpha#298]
- [context.now](#sec-1)

```yaml
version: 0.1.6
# ...
base
  # ...
  start_date: 2018-01-01
  end_date: 2018-04-24
  run_type: p # 模拟交易 或者 run_type: b 实盘交易
  # ...
```
# context.now<a id="sec-1"></a>

-   **期待值:**

2018-04-24 10:00:00

-   **实际值:**

2018-01-01 0:0:0
