### ISSUE TITLE
建议restore Portfolio的state采用 merge 方式, 而不是现在的重写方式.

### ISSUE THREAD

**Issue by yssource** [ricequant/rqalpha#311]
目前 RQA 处理方式是 直接覆盖 初始的 portfolio, 并不是 merge 方式. 会造成 config.yaml 中的 accounts 和 init_positions 信息丢失.

---

我的工作流: 采用 persist, 先回测, 实盘时再将券商真实仓位初始化入config.yaml 中<a id="sec-1"></a>

-   策略回测:
run_type: b
end_date:昨天

-   实盘交易:
run_type: p
start_date:今天
end_date:今天
```yaml
...
accounts:
  stock: 10000
  future: ~
init_positions: 000001.XSHG:100
...
```

**Comment by yssource** [comment]
觉得, 应该在这里 将 init_portfolio 和 state 取回来的 portfolio 进行 **merge**, 
https://github.com/ricequant/rqalpha/blob/develop/rqalpha/model/portfolio.py#L64-L72
现在 RQA 的处理就是 丢掉 init portfolio, 而留下 持久化的 state.
如果我在回测后, 想要将真实的券商仓位放入实盘中, 就很有必要 merge.
你觉得呢? @Cuizi7 
谢谢考虑一下.

**Comment by yssource** [comment]
代码中 merge 也不是好的方案. 因为每次 RQA run 都会 将 config.yaml 中的 accounts merge 再 persist, 会带来重复的 merge & persist. 
我的 workaround 是: 实盘时, 手动修改 ./persist/portfolio, 将券商仓位加入 portfolio. 每次run时就不需要merge了, 同时也保证了实际仓位的 persist.
- 暂时保留这个 issue opened, 或许别人也会有遇到同样的需求, 或者有更好的解决方案.
- @Cuizi7 如果觉得这建议没有什么实际意义, 请 close 掉这个 issue.

**Comment by yssource** [comment]
或者在 config.yaml `accounts` 和 `init_positions`, 下面提供一个merge 开关, 让用户在自由选择是否需要 merge

``` yaml
...
accounts:
   merge: true
    stock: 10000
    future: ~
init_positions: 000001.XSHG:100 #  merge: true
...
```
-----
另外, 目前在config.yaml init_positions 是和 accounts 并行的, 是否将 init_positions 移入 accounts 下一层, 更加合理呢?
