### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by OOXXXXOO** [ricequant/rqalpha#573]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

配置文件  config.yaml

```
# config.yml
base:
  # 启动的策略文件路径
  strategy_file: abu.py
  # 回测起始日期
  start_date: 2015-06-01
  # 回测结束日期(如果是实盘，则忽略该配置)
  end_date: 2050-01-01
  # 目前支持 `1d` (日线回测) 和 `1m` (分钟线回测)，如果要进行分钟线，请注意是否拥有对应的数据源，目前开源版本是不提供对应的数据源的。
  frequency: 1d
  # Benchmark，如果不设置，默认没有基准参照。
  benchmark: ~
  accounts:
    # 设置 股票为交易品种  初始资金为 100000 元
    stock:  100000
extra:
  # 开启日志输出
  log_level: verbose
mod:
  sys_analyser:
    enabled: true
    # 开启 plot 功能
    plot: true
```

策略 abu.py
```python
def init(context):
    context.s1 = "IF88"
    subscribe(context.s1)
    logger.info("Interested in: " + str(context.s1))


def handle_bar(context, bar_dict):
    buy_open(context.s1, 1)


__config__ = {
    "base": {
        "start_date": "2015-01-09",
        "end_date": "2015-03-09",
        "frequency": "1d",
        "matching_type": "current_bar",
        "benchmark": None,
        "accounts": {
            "future": 1000000
        }
    },
    "extra": {
        "log_level": "error",
    },
    "mod": {
        "sys_progress": {
            "enabled": True,
            "show": True,
        },
    },
}
```

命令：
`rqalpha run`

## 1. RQAlpha的版本
4.2.2
## 2. Python的版本
3.7
## 3. 是Windows/Linux/MacOS or others?
Ubuntu 18.04 Docker Image
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
以上
## 5. 您出现的错误堆栈日志信息

locale.Error: unsupported locale setting
Traceback (most recent call last):
  File "/opt/conda/bin/rqalpha", line 8, in <module>
    sys.exit(entry_point())
  File "/opt/conda/lib/python3.7/site-packages/rqalpha/__main__.py", line 23, in entry_point
    cli(obj={})
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/rqalpha/cmds/run.py", line 68, in run
    cfg = parse_config(kwargs, config_path=config_path, click_type=True, source_code=source_code)
  File "/opt/conda/lib/python3.7/site-packages/rqalpha/utils/config.py", line 172, in parse_config
    set_locale(config.extra.locale)
  File "/opt/conda/lib/python3.7/site-packages/rqalpha/utils/config.py", line 120, in set_locale
    locale.setlocale(locale.LC_ALL, "en_US.UTF-8")
  File "/opt/conda/lib/python3.7/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
